### ISSUE TITLE
WorkInProgress collection of potential improvements

### ISSUE THREAD

**Issue by hiddenalpha** [swisspost/gateleen#417]
Not an issue in that sense. But more a place where I can collect random stuff seen, which probably has potential for improvement (*measured by my personal opinion*).

**HINT**: I'll occasionally update this issue if I discover more.

---
IMHO would be worth commenting why we [instantiate a string](https://github.com/swisspush/gateleen/blob/v1.2.9/gateleen-core/src/main/java/org/swisspush/gateleen/core/util/ExpansionDeltaUtil.java#L284) from the [buffer we got as argument](https://github.com/swisspush/gateleen/blob/v1.2.9/gateleen-core/src/main/java/org/swisspush/gateleen/core/util/ExpansionDeltaUtil.java#L269) just to [pass it to JsonObject ctor](https://github.com/swisspush/gateleen/blob/v1.2.9/gateleen-core/src/main/java/org/swisspush/gateleen/core/util/ExpansionDeltaUtil.java#L287) which already would accept a buffer directly.

---
[HookHandlers handle method](https://github.com/swisspush/gateleen/blob/v1.2.9/gateleen-hook/src/main/java/org/swisspush/gateleen/hook/HookHandler.java#L461) in my experience is a relatively hot code path as eg in our use-case its called quite often. Therefore I whonder why we are [calling several methods](https://github.com/swisspush/gateleen/blob/v1.2.9/gateleen-hook/src/main/java/org/swisspush/gateleen/hook/HookHandler.java#L467-L485), and then in each of them we [first do a string search before doing the (*IMHO*) more lightweight int comparison](https://github.com/swisspush/gateleen/blob/v1.2.9/gateleen-hook/src/main/java/org/swisspush/gateleen/hook/HookHandler.java#L1610-L1612). Maybe *slightly* more efficient when doing the int comparison 1st. So instead:
```java
request.uri().contains(HOOKS_LISTENERS_URI_PART) && HttpMethod.PUT == request.method()
```
We would have:
```java
HttpMethod.PUT == request.method() && request.uri().contains(HOOKS_LISTENERS_URI_PART)
```

---
Why do we [register a body handler](https://github.com/swisspush/gateleen/blob/v1.2.9/gateleen-expansion/src/main/java/org/swisspush/gateleen/expansion/ExpansionHandler.java#L546) collecting everything into memory, just to [ignore the collected contents](https://github.com/swisspush/gateleen/blob/v1.2.9/gateleen-expansion/src/main/java/org/swisspush/gateleen/expansion/ExpansionHandler.java#L552-L557) in case status code is not what we did expect?

Why couldn't we consult the response code beforehand? (*Before even registering a body handler*)

---
Candidates that probably should use [parameterized logging](https://www.tutorialspoint.com/slf4j/slf4j_parameterized_logging.htm):
- https://github.com/swisspush/gateleen/blob/v1.1.61/gateleen-kafka/src/main/java/org/swisspush/gateleen/kafka/KafkaHandler.java#L154
- https://github.com/swisspush/gateleen/blob/v1.1.61/gateleen-kafka/src/main/java/org/swisspush/gateleen/kafka/KafkaHandler.java#L162

---
Logs containing (*probably expensive*) evaluations should be guarded by isEnabled checks.
- https://github.com/swisspush/gateleen/blob/v1.1.61/gateleen-kafka/src/main/java/org/swisspush/gateleen/kafka/KafkaMessageSender.java#L39
- https://github.com/swisspush/gateleen/blob/v1.1.61/gateleen-kafka/src/main/java/org/swisspush/gateleen/kafka/KafkaMessageSender.java#L41

---
Logs should not call `toString()` but let the logger do this. This way `toString()` overhead only is done if logger is active.
- https://github.com/swisspush/gateleen/blob/v1.1.61/gateleen-kafka/src/main/java/org/swisspush/gateleen/kafka/KafkaHandler.java#L131

**Comment by mcweba** [comment]
About using the _isEnabled_ checks. When using the parameterized logging with slf4j, the usage of _isEnabled_ decreases the performance. See [SLF4J FAQ](https://www.slf4j.org/faq.html#logging_performance)

**Comment by hiddenalpha** [comment]
- Link 1 -> `payload.toString()` MUST construct the string everytime. This also MUST be done in case of parameterized logging.
- Link 2 & 3 -> `event.result().toJson()` also will construct the json all the time. Even when not used by logger. But we MUST construct it so we can pass it as a parameter to the logger.
