### ISSUE TITLE
Forward original payload to delegated destination

### ISSUE THREAD

**Issue by mcweba** [swisspost/gateleen#451]
With the delegate feature, one is able to peform two things with delegates:
* Execute a new request with a new destination and a new payload
* Transform the json payload of the original request and send it to a new destination

With the current implementation, it is not possible to reuse the orignal payload and send it to a new destination. This feature can be best explained by the [Tee](https://linuxize.com/post/linux-tee-command/) command in Linux.

To achieve this, a new property called _copy_ could be introduced. Finally there can be only one of the three properties be present in a delegate:
* payload
* transform or transformWithMetadata
* copy

The need for this feature came up, when we wanted to delegate non-json payloads.

**Comment by Kusig** [comment]
So it is basically a NOP Transformation?
The only open question I have is if we should allow really any body content here and if this might introduce any kind of security issue if there is no transformation in between as it will become a black-box mover?

**Comment by mcweba** [comment]
Yes I we want to handle this case as a transformation it would be a NOP. Regarding security, we have the same situation for a regular request forwarding (Forwarder) because anything can be forwarded. The only difference to the delegate is, that a copy of the request is forwarded somewhere else.

**Comment by lbovet** [comment]
If we don't do anything on the original payload, in what it differs from a routing rule or a hook?

**Comment by mcweba** [comment]
@lbovet good point. It differs from a regular routing rule because it duplicates the request. With a routing rule only, you can forward (or route) only to a single destination.
I also thought about using hooks instead of extending the delegates. In the current implementation of a hook, it's not possible to use a destination including wildcards like the `$1`. You can just define a "static" destination without any url parameters and url segments from the original request.
Instead of extending the delegates, we could also extend the hooks to be more flexible.

**Comment by mcweba** [comment]
See #606. It probably makes more sense to extend the hook feature to accept wildcards.
